version: "3.8"

services:
  sonarqube:
    image: ${SONAQUBE_IMAGE_VERSION}
    container_name: ${SONAQUBE_CONTAINER_NAME}
    restart: ${ALWAYS}
    expose:
      - ${SONAQUBE_EXPOSE_PORT}
    ports:
      - ${SONAQUBE_LOCALHOST_PORT}:${SONAQUBE_CONTAINER_PORT}
    networks:
      sonarnet:
        ipv4_address: ${SONARQUBE_IP}
    environment:
      - sonar.jdbc.url=${POSTGRES_URL}
      - sonar.jdbc.username=${POSTGRES_USER}
      - sonar.jdbc.password=${POSTGRES_PASSWORD}
      - stop-timeout=${SONARQUBE_STOP_TIMEOUT}
    volumes:
      - ${SONARQUBE_VOLUME_CONF_LOCALHOST}:${SONARQUBE_VOLUME_CONF_CONTAINER}
      - ${SONARQUBE_VOLUME_DATA_LOCALHOST}:${SONARQUBE_VOLUME_DATA_CONTAINER}
      - ${SONARQUBE_VOLUME_EXTENSIONS_LOCALHOST}:${SONARQUBE_VOLUME_EXTENSIONS_CONTAINER}
      - ${SONARQUBE_VOLUME_LOGS_LOCALHOST}:${SONARQUBE_VOLUME_LOGS_CONTAINER}
  db:
    image: ${POSTGRES_IMAGE_VERSION}
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: ${ALWAYS}
    networks:
      sonarnet:
        ipv4_address: ${POSTGRES_IP}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "${POSTGRES_VOLUME_DATA_LOCALHOST}:${POSTGRES_VOLUME_DATA_CONTAINER}"

networks:
  sonarnet:
    driver: ${NETWORK_BRIDGE}
    ipam:
      driver: ${NETWORK_DEFAULT}
      config:
        - subnet: ${NETWORK_CONFIG_SUBNET}